ZDCC: GuiCalculator Class Reference
GuiCalculator Class Reference
#include <guicalculator.h>
Public Member Functions
GuiCalculator (QWidget *parent=nullptr)
Construct a new Gui Calculator:: Gui Calculator object.
~GuiCalculator ()
Destroy the Gui Calculator:: Gui Calculator object.
Private Slots
void numberPressed ()
Calculator functions.
void clearPressed ()
Clear button handling.
void operationPressed ()
Operation switch.
void equalsPressed ()
Executing operations and getting result.
void floatPressed ()
Float point number handling.
void facPressed ()
Factorial handling.
void helpPressed ()
Help pop up window.
void logPressed ()
Natural logarithm handling.
void changeSignPressed ()
Changing sign of a number via button on calculator.
Private Attributes
Ui::GuiCalculator * ui
Detailed Description
Definition at line 24 of file guicalculator.h.
Constructor & Destructor Documentation
GuiCalculator()
GuiCalculator::GuiCalculator (QWidget * parent = nullptr)
Construct a new Gui Calculator:: Gui Calculator object.
Parameters
parent
Display ans.
setting numButtons.
setting delete&Clear.
setting float button.
setting operation.
setting fac.
setting log.
setting equals button.
Definition at line 35 of file guicalculator.cpp.
     : QMainWindow(parent)
     , ui(new Ui::GuiCalculator)
 {
     ui->setupUi(this);
     ui->Display->setText(QString::number(ans));
     connect(ui->Num0, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num1, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num2, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num3, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num4, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num5, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num6, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num7, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num8, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->Num9, SIGNAL(released()), this, SLOT (numberPressed()));
     connect(ui->clearButton, SIGNAL(released()), this, SLOT (clearPressed()));
     connect(ui->floatButton, SIGNAL(released()), this, SLOT (floatPressed()));
     connect(ui->addButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->subButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->mulButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->divButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->powerButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->sqrtButton, SIGNAL(released()), this, SLOT (operationPressed()));
     connect(ui->facButton, SIGNAL(released()), this, SLOT (facPressed()));
     connect(ui->logButton, SIGNAL(released()), this, SLOT (logPressed()));
     connect(ui->eqButton, SIGNAL(released()), this, SLOT (equalsPressed()));
     //setting help button.
     connect(ui->helpButton, SIGNAL(released()), this, SLOT (helpPressed()));
     //setting change sign button.
     connect(ui->ChangeSign, SIGNAL(released()), this, SLOT (changeSignPressed()));
 }
References ans, changeSignPressed(), clearPressed(), equalsPressed(), facPressed(), floatPressed(), helpPressed(), logPressed(), numberPressed(), operationPressed(), and ui.
~GuiCalculator()
GuiCalculator::~GuiCalculator ()
Destroy the Gui Calculator:: Gui Calculator object.
Definition at line 90 of file guicalculator.cpp.
 {
     delete ui;
 }
References ui.
Member Function Documentation
changeSignPressed
void GuiCalculator::changeSignPressed () private slot
Changing sign of a number via button on calculator.
Definition at line 302 of file guicalculator.cpp.
 {
     QString displayValue = ui->Display->text();
     double dblValue = displayValue.toDouble();
     dblValue = dblValue * -1;
     ui->Display->setText(QString::number(dblValue));
 }
References ui.
Referenced by GuiCalculator().
clearPressed
void GuiCalculator::clearPressed () private slot
Clear button handling.
Definition at line 136 of file guicalculator.cpp.
 {
     divBool = false;
     mulBool = false;
     addBool = false;
     subBool = false;
     powerBool = false;
     sqrtBool = false;
     firstNum = false;
     ui->Display->setText("0");
 }
References addBool, divBool, firstNum, mulBool, powerBool, sqrtBool, subBool, and ui.
Referenced by GuiCalculator().
equalsPressed
void GuiCalculator::equalsPressed () private slot
Executing operations and getting result.
Definition at line 200 of file guicalculator.cpp.
 {
     double num = 0.0;
     QString displayValue = ui->Display->text();
     double dblValue = displayValue.toDouble();
     if(addBool || subBool || divBool || mulBool || powerBool || sqrtBool)
     {
         if(addBool)
         {
             //INSERT FUNCTION
             num = sum(ans, dblValue);
         }
         else if(subBool)
         {
             num = sub(ans, dblValue);
         }
         else if(divBool)
         {
             if(dblValue == 0)
             {
                 ui->Display->setText("Syntax error");
                 return;
             }
             else
             {
                 num = div(ans, dblValue);
             }
         }
         else if(mulBool)
         {
             num = mul(ans, dblValue);
         }
         else if(powerBool)
         {
             if(dblValue - int(dblValue) != 0)
             {
                 ui->Display->setText("Syntax error");
                 return;
             }
             else
             {
                 num = power(ans, dblValue);
             }
         }
         else if(sqrtBool)
         {
             if((dblValue <= 0) || (dblValue - int(dblValue) != 0) || (ans < 0 && int(dblValue) % 2 == 0))
             {
                 ui->Display->setText("Syntax error");
                 return;
             }
             else
             {
                 num = rooting(ans, dblValue);
             }
         }
     }
     ui->Display->setText(QString::number(num));
 }
References addBool, ans, div(), divBool, mul(), mulBool, power(), powerBool, rooting(), sqrtBool, sub(), subBool, sum(), and ui.
Referenced by GuiCalculator().
facPressed
void GuiCalculator::facPressed () private slot
Factorial handling.
Definition at line 264 of file guicalculator.cpp.
 {
     QString displayValue = ui->Display->text();
     double dblValue = displayValue.toDouble();
     if(dblValue - int(dblValue) != 0)
     {
         ui->Display->setText("Syntax error");
     }
     else
     {
         dblValue = fac(dblValue);
         ui->Display->setText(QString::number(dblValue));
     }
 }
References fac(), and ui.
Referenced by GuiCalculator().
floatPressed
void GuiCalculator::floatPressed () private slot
Float point number handling.
Definition at line 125 of file guicalculator.cpp.
 {
     QString displayValue = ui->Display->text();
     QString newValue = displayValue + ".";
     ui->Display->setText(newValue);
 }
References ui.
Referenced by GuiCalculator().
helpPressed
void GuiCalculator::helpPressed () private slot
Help pop up window.
Definition at line 314 of file guicalculator.cpp.
 {
     helpWindow window;
     window.setModal(true);
     window.exec();
 }
Referenced by GuiCalculator().
logPressed
void GuiCalculator::logPressed () private slot
Natural logarithm handling.
Definition at line 283 of file guicalculator.cpp.
 {
     QString displayValue = ui->Display->text();
     double dblValue = displayValue.toDouble();
     if(dblValue <= 0)
     {
         ui->Display->setText("Syntax error");
     }
     else
     {
         dblValue = ln(dblValue);
         ui->Display->setText(QString::number(dblValue));
     }
 }
References ln(), and ui.
Referenced by GuiCalculator().
numberPressed
void GuiCalculator::numberPressed () private slot
Calculator functions.
Number pressed on calculator handling.
Definition at line 100 of file guicalculator.cpp.
 {
     QPushButton * buttonPressed = (QPushButton *)sender();
     QString value = buttonPressed->text();
     QString displayValue = ui->Display->text();
     if(firstNum == false)
     {
         //rewrite number on display
         ui->Display->setText(value);
         firstNum = true;
     }
     else
     {
         //add number to displayed number to create new value
         QString newValue = displayValue + value;
         //double doubleNewValue = newValue.toDouble();
         ui->Display->setText(newValue);
     }
 }
References firstNum, and ui.
Referenced by GuiCalculator().
operationPressed
void GuiCalculator::operationPressed () private slot
Operation switch.
Clearing operation buttons.
Definition at line 152 of file guicalculator.cpp.
 {
     divBool = false;
     mulBool = false;
     addBool = false;
     subBool = false;
     powerBool = false;
     sqrtBool = false;
     firstNum = false;
     QPushButton * buttonPressed = (QPushButton *)sender();
     QString operatorPressed = buttonPressed->objectName();
     QString pressedValue = ui->Display->text();
     double dblPressedValue = pressedValue.toDouble();
     ans = dblPressedValue;
     if(QString::compare(operatorPressed, "addButton", Qt::CaseInsensitive)==0)
     {
         addBool = true;
     }
     else if(QString::compare(operatorPressed, "subButton", Qt::CaseInsensitive)==0)
     {
         subBool = true;
     }
     else if(QString::compare(operatorPressed, "divButton", Qt::CaseInsensitive)==0)
     {
         divBool = true;
     }
     else if(QString::compare(operatorPressed, "mulButton", Qt::CaseInsensitive)==0)
     {
         mulBool = true;
     }
     else if(QString::compare(operatorPressed, "powerButton", Qt::CaseInsensitive)==0)
     {
         powerBool = true;
     }
     else if(QString::compare(operatorPressed, "sqrtButton", Qt::CaseInsensitive)==0)
     {
         sqrtBool = true;
     }
     ui->Display->setText("");
 }
References addBool, ans, divBool, firstNum, mulBool, powerBool, sqrtBool, subBool, and ui.
Referenced by GuiCalculator().
Member Data Documentation
ui
Ui::GuiCalculator* GuiCalculator::ui private
Definition at line 33 of file guicalculator.h.
Referenced by changeSignPressed(), clearPressed(), equalsPressed(), facPressed(), floatPressed(), GuiCalculator(), logPressed(), numberPressed(), operationPressed(), and ~GuiCalculator().
The documentation for this class was generated from the following files:
src/guicalculator.h
src/guicalculator.cpp