ZDCC: src/math_lib.h File Reference
math_lib.h File Reference
Implementation of math library.
#include <math.h>
#include <stdexcept>
Functions
double sum (const double num1, const double num2)
Summarization of two numbers.
double sub (const double num1, const double num2)
Subtraction of two numbers.
double mul (const double num1, const double num2)
Multiplication of two numbers.
double div (const double num1, const double num2)
Division of two nubmers.
int fac (double num1)
Factorial of a number.
double power (const double num1, const double num2)
Power of num1 to num2.
double rooting (const double num1, const double num2)
Root of num1 to num2.
double ln (const double num1)
Natural logarithm of num1.
Detailed Description
Implementation of math library.
Author
Maxim Plicka, VUT FIT Brno, xplic.nosp@m.k04@.nosp@m.fit.v.nosp@m.utbr.nosp@m..cz, VUT FIT Brno
Date
26.03.2021
Definition in file math_lib.h.
Function Documentation
div()
double div (const double num1, const double num2)
Division of two nubmers.
Warning
Cannot divide by zero
Parameters
num1
num2
Returns
double
Checking for dividing by zero.
Definition at line 56 of file math_lib.h.
 {
     if(num2 == 0)
     {
         throw std::runtime_error("Cannot divide by zero.");
         return 0;
     }
     else{
         return(num1/num2);
     }
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().
fac()
int fac (double num1)
Factorial of a number.
Warning
Must be natural number
Parameters
num1
Returns
int
Control for natural numbers.
Checking if num1 is greater than zero.
Checking if num1 is lesser than zero.
Definition at line 75 of file math_lib.h.
 {
     if(num1 - int(num1) != 0)
     {
         throw std::runtime_error("Must be natural number.");
         return 0;
     }
     int result = 1;
     int x = abs(num1);
     if(num1 >= 0)
     {
         for(int i = 1; i <= x; i++)
         {
             result *= i;
         }
     }
     if(num1 < 0)
     {
         for(int i = 1; i <= x; i++)
         {
             result *= i;
         }
         result *= -1;
     }
     return(result);
 }
Referenced by GuiCalculator::facPressed(), and TEST().
ln()
double ln (const double num1)
Natural logarithm of num1.
Warning
Root must be greater than zero
Parameters
num1
Returns
double
num1 must be greater than zero.
Definition at line 176 of file math_lib.h.
 {
     if(num1 <= 0)
     {
         throw std::runtime_error("Root must be greater than zero.");
     }
     return (log(num1));
 }
Referenced by GuiCalculator::logPressed(), and TEST().
mul()
double mul (const double num1, const double num2)
Multiplication of two numbers.
Parameters
num1
num2
Returns
double
Definition at line 44 of file math_lib.h.
 {
     return(num1 * num2);
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().
power()
double power (const double num1, const double num2)
Power of num1 to num2.
Warning
Must be natural number
Parameters
num1
num2
Returns
double
Checking for natural numbers.
Definition at line 116 of file math_lib.h.
 {
     if(num2 - int(num2) != 0)
     {
         throw std::runtime_error("Must be natural number.");
     }
     double result = pow(num1,num2);
     return(result);
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().
rooting()
double rooting (const double num1, const double num2)
Root of num1 to num2.
Warning
Must be natural number
Root must be greater than zero
Does not exist
Parameters
num1
num2
Returns
double
Checking for negative root.
Checking if num2 is natural number.
Checking if num1 is lesser than zero.
Checking for invalid root of negative number.
Definition at line 137 of file math_lib.h.
{
     double result;
     if (num2 <= 0) {
         throw std::runtime_error("Root must be greater than zero.");
     }
     int x = int(num2);
     if((num2 - x) != 0)
     {
         throw std::runtime_error("Must be natural number.");
     }
     if (num1 < 0)
     {
         if(int(num2) % 2 == 0)
         {
             throw std::runtime_error("Doesnt exist.");
         }
         result = pow(abs(num1),1/num2);
         return(result*(-1));
     }
     result = pow(num1,1/num2);
     return(result);
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().
sub()
double sub (const double num1, const double num2)
Subtraction of two numbers.
Parameters
num1
num2
Returns
double
Definition at line 32 of file math_lib.h.
 {
     return(num1-num2);
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().
sum()
double sum (const double num1, const double num2)
Summarization of two numbers.
Parameters
num1
num2
Returns
double
Definition at line 20 of file math_lib.h.
 {
     return(num1+num2);
 }
Referenced by GuiCalculator::equalsPressed(), and TEST().